export const initialProductData = {
	title: "",
	description: "",
	basePrice: "",
	discountPercent: "",
	weight: "",
	quantity: "",
	article: "",
	brand: "",
	manufacturer: "",
	isHealthyFood: false,
	isNonGMO: false,
	categories: [],
	tags: [],
};
